title: Rideau Rollers Blog 
description: The blog of Ottawa's only roller skate store! 
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme
url: "https://blog.rideaurollers.com"
paginate: 5
paginate_path: /page:num/
