title: Rideau Rollers Blog 
description: The blog of Ottawa's only roller skate store! 
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme
sidebar:
- coc
- label: Where to Skate
  children:
  - 2024-jan 
