title: Rideau Rollers Blog 
description: The blog of Ottawa's only roller skate store! 
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
url: "https://blog.rideaurollers.com"
paginate: 5
paginate_path: /page:num/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
author:
  name             : "Rideau Rollers"
  avatar           : "assets/images/store-front.png" 
  bio              : "Ottawa's store for all things roller skating!"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sales@rideaurollers.com"
    - label: "Store"
      icon: "fas fa-fw fa-link"
      url: "https://rideaurollers.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/rideaurollers"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rideau_rollers"
